
job-tmpl: &job-tmpl
  machine: true

  working_directory: ~/src

  steps:
    - run: env
    - checkout
    - run:
        name: Install Python 
        command: | 
          if [[ $PYTHON == "python3.6" ]]; then 
            sudo bash -c "yes | add-apt-repository ppa:jonathonf/python-3.6 && apt-get update && apt-get install -y python3.6"
          fi
          if [[ $PYTHON == "python3.4" ]]; then 
            sudo bash -c "yes | add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get install -y python3.4"
          fi
          curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo $PYTHON
          sudo $PYTHON -m pip install --upgrade pip
          sudo $PYTHON -m pip install --upgrade virtualenv
 
    - run: 
        name: Create venv and install extras
        command: | 
          $PYTHON -m virtualenv venv
          . venv/bin/activate
          pip install       \
              pypandoc       \
              wheel          \
              coverage       \
              python-jenkins \
              redis          \
              pymongo        \
              psycopg2       \
              boto3          \
              rethinkdb

    - run: 
        name: Build and install dists
        command: |
          . venv/bin/activate
          ./foreach.sh 'cp ../VERSION ../CHANGES.md ../common_setup.py ../MANIFEST.in ../LICENSE .'
          ./foreach.sh 'pip install -e .'

    - run: 
        name: Run Tests
        command: |
          . venv/bin/activate
          export DEBUG=1
          ./foreach.sh 'python setup.py test'
          ./foreach.sh 'echo $PKG | sed s/-/_/g | xargs -Ipysrc coverage run -p --source=pysrc setup.py test -sv -ra || touch ../FAILED-$PKG'
          compgen -G 'FAILED-*' && exit 1
                     
    - run: 
        name: Update Apt-Sources
        command: | 
          source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
          wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
          source /etc/lsb-release && echo "deb http://pkg.jenkins-ci.org/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list
          wget -qO- https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
          echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
          sudo apt-get update
    - run: 
        name: Install Postgresql
        command: | 
          sudo apt-get install postgresql postgresql-contrib
          sudo service postgresql stop; sudo update-rc.d postgresql disable;
    - run: 
        name: Install Redis
        command: | 
          sudo apt-get install redis-server pandoc subversion graphviz
    - run: 
        name: Install Rethinkdb
        command: | 
          sudo apt-get install rethinkdb
          sudo service rethinkdb stop; sudo update-rc.d rethinkdb disable;
    - run: 
        name: Install Jenkins
        command: | 
          sudo apt-get install jenkins
          sudo service jenkins stop; sudo update-rc.d jenkins disable;
    - run: 
        name: Install Mongodb
        command: | 
          sudo apt-get install mongodb-org mongodb-org-server
    - run: 
        name: Install Minio
        command: | 
          wget https://dl.minio.io/server/minio/release/linux-amd64/minio -O /tmp/minio
          sudo mv /tmp/minio /usr/local/bin/minio
          sudo chmod a+x /usr/local/bin/minio

version: 2
jobs:
  py27: 
    <<: *job-tmpl
    environment:
      PYTHON: "python2.7"

  py34: 
    <<: *job-tmpl
    environment:
      PYTHON: "python3.4"

  py35: 
    <<: *job-tmpl
    environment:
      PYTHON: "python3.5"

  py36: 
    <<: *job-tmpl
    environment:
      PYTHON: "python3.6"

workflows:
  version: 2
  pytest-plugins:
    jobs:
      - py27
      - py34
      - py35
      - py36
